services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.1
    environment:
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring856hbv23
      MYSQL_DATABASE: schoolmng
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 9306:3306
    networks:
      schoolmng-net:


  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_OUTGOING_USER=hello
      - MAILDEV_OUTGOING_PASS=hello
    ports:
      - "9080:1080"
      - "9025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      schoolmng-net:


  schoolmng-web:
    container_name: schoolmng-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/schoolmng
      - spring.datasource.username=spring
      - spring.datasource.password=spring856hbv23
      - spring.mail.host=maildev
      - spring.mail.port=1025
      - spring.mail.username=hello
      - spring.mail.password=hello
      - spring.mail.properties.mail.smtp.ssl.trust=*
      - spring.mail.properties.mail.smtp.auth=false
      - spring.mail.properties.mail.smtp.starttls.enable=true
      - spring.mail.properties.mail.smtp.connectiontimeout=5000
      - spring.mail.properties.mail.smtp.timeout=3000
      - spring.mail.properties.mail.smtp.writetimeout=5000
    networks:
      schoolmng-net:
    restart: on-failure

networks:
  schoolmng-net: